// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmoothCareers.Data;

#nullable disable

namespace SmoothCareers.Migrations
{
    [DbContext(typeof(SmoothCareersContext))]
    [Migration("20260111045601_AddJobSeekerDbSet")]
    partial class AddJobSeekerDbSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "cd2bcf0c-20db-474f-8407-5a6b159518bc",
                            Name = "Employer",
                            NormalizedName = "EMPLOYER"
                        },
                        new
                        {
                            Id = "dd2bcf0c-20db-474f-8407-5a6b159518bd",
                            Name = "JobSeeker",
                            NormalizedName = "JOBSEEKER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        },
                        new
                        {
                            UserId = "b1a2c3d4-e5f6-47a8-9b01-112233445566",
                            RoleId = "cd2bcf0c-20db-474f-8407-5a6b159518bc"
                        },
                        new
                        {
                            UserId = "c2b3a4d5-e6f7-48b9-8c02-667788990011",
                            RoleId = "dd2bcf0c-20db-474f-8407-5a6b159518bd"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SmoothCareers.Data.SmoothCareersUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b65b72bf-cdae-49b0-a0cc-fcb149f33cdb",
                            Email = "admin@smoothcareers.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SMOOTHCAREERS.COM",
                            NormalizedUserName = "ADMIN@SMOOTHCAREERS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE3CX4S7hGqhMoof6Lwiz0sftqbpK8LIPjkvT5wnMRbYyQX0++Rer9SzHpKP3h3JHw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "01b37684-d0b2-411e-b28b-6f4b03f9174a",
                            TwoFactorEnabled = false,
                            UserName = "admin@smoothcareers.com"
                        },
                        new
                        {
                            Id = "b1a2c3d4-e5f6-47a8-9b01-112233445566",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4f899f22-3c1b-459b-8da8-9d2dfcd0f176",
                            Email = "employer@smoothcareers.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPLOYER@SMOOTHCAREERS.COM",
                            NormalizedUserName = "EMPLOYER@SMOOTHCAREERS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEExOteglzeDmeYdxWze0vCIY4G7VIEJFHW8kFPciSD1wTfMsA0po2j36tvBl/l8LBQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4f8e07bc-c8a4-4f14-b43c-f349a47388c1",
                            TwoFactorEnabled = false,
                            UserName = "employer@smoothcareers.com"
                        },
                        new
                        {
                            Id = "c2b3a4d5-e6f7-48b9-8c02-667788990011",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "40291fdf-36ff-4d00-850b-73630af9413a",
                            Email = "jobseeker@smoothcareers.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JOBSEEKER@SMOOTHCAREERS.COM",
                            NormalizedUserName = "JOBSEEKER@SMOOTHCAREERS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEB7xN8w87eIYJLqiqcz+CPj7iI8XviepdLZQSz/6KxHA8xVoy/8CVdF5Y1M+wvaX4Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b61a0610-8163-45f8-ac39-e3ebc197be2b",
                            TwoFactorEnabled = false,
                            UserName = "jobseeker@smoothcareers.com"
                        });
                });

            modelBuilder.Entity("SmoothCareers.Domain.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobPostId")
                        .HasColumnType("int");

                    b.Property<int>("JobSeekerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId");

                    b.HasIndex("JobSeekerId");

                    b.ToTable("Application");
                });

            modelBuilder.Entity("SmoothCareers.Domain.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "SmoothCareers Demo Pte Ltd",
                            DateCreated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "",
                            Location = ""
                        });
                });

            modelBuilder.Entity("SmoothCareers.Domain.JobCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(8871),
                            DateUpdated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(8881),
                            Name = "Software Engineering",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(8883),
                            DateUpdated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(8884),
                            Name = "Data & Analytics",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(8885),
                            DateUpdated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(8886),
                            Name = "Cybersecurity",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(8887),
                            DateUpdated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(8888),
                            Name = "UI/UX Design",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(8889),
                            DateUpdated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(8889),
                            Name = "IT Support",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(8890),
                            DateUpdated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(8891),
                            Name = "Business & Operations",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("SmoothCareers.Domain.JobPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<int>("JobCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkArrangementId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("JobCategoryId");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("WorkArrangementId");

                    b.ToTable("JobPost");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePosted = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Build CRUD features with ASP.NET Core MVC, EF Core, SQL Server. Work with Git branching and code reviews.",
                            EmployerId = 1,
                            JobCategoryId = 1,
                            JobTypeId = 1,
                            Location = "Singapore (Tampines)",
                            Salary = 4200m,
                            Title = "Junior Full-Stack Developer (.NET)",
                            WorkArrangementId = 2
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePosted = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Support automation workflows for Outlook/Excel and document processes. Basic regex and debugging is a plus.",
                            EmployerId = 1,
                            JobCategoryId = 1,
                            JobTypeId = 2,
                            Location = "Singapore (Remote)",
                            Salary = 1200m,
                            Title = "RPA Developer (Intern) - UiPath",
                            WorkArrangementId = 3
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePosted = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clean and analyze datasets using Python (Pandas) and build visual insights. Basic SQL required.",
                            EmployerId = 1,
                            JobCategoryId = 2,
                            JobTypeId = 1,
                            Location = "Singapore (Central)",
                            Salary = 3800m,
                            Title = "Data Analyst (Entry-Level)",
                            WorkArrangementId = 2
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePosted = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create wireframes, user flows, and prototypes in Figma. Assist with usability testing and design systems.",
                            EmployerId = 1,
                            JobCategoryId = 3,
                            JobTypeId = 2,
                            Location = "Singapore (CBD)",
                            Salary = 1200m,
                            Title = "UI/UX Designer (Intern)",
                            WorkArrangementId = 2
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePosted = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Provide onsite support: Windows troubleshooting, printer issues, domain join, OneDrive/Outlook setup.",
                            EmployerId = 1,
                            JobCategoryId = 4,
                            JobTypeId = 1,
                            Location = "Singapore (Central)",
                            Salary = 2800m,
                            Title = "IT Support Technician (Hospital)",
                            WorkArrangementId = 1
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePosted = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Execute test cases, report defects, and validate fixes. Exposure to test automation is a plus.",
                            EmployerId = 1,
                            JobCategoryId = 1,
                            JobTypeId = 3,
                            Location = "Singapore (East)",
                            Salary = 3200m,
                            Title = "Software QA Tester (Contract)",
                            WorkArrangementId = 2
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePosted = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Assist with networking tasks: IP config, connectivity troubleshooting, and basic device setup.",
                            EmployerId = 1,
                            JobCategoryId = 4,
                            JobTypeId = 1,
                            Location = "Singapore (North)",
                            Salary = 3400m,
                            Title = "Network Support Engineer (Entry-Level)",
                            WorkArrangementId = 1
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePosted = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Maintain site pages, fix UI bugs, and implement small features. HTML/CSS/JS and basic .NET helpful.",
                            EmployerId = 1,
                            JobCategoryId = 1,
                            JobTypeId = 4,
                            Location = "Singapore (Hybrid)",
                            Salary = 2200m,
                            Title = "Web Developer (Part-Time)",
                            WorkArrangementId = 2
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePosted = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Support model training experiments, data preprocessing, and evaluation. Python required.",
                            EmployerId = 1,
                            JobCategoryId = 2,
                            JobTypeId = 3,
                            Location = "Singapore (Remote)",
                            Salary = 4500m,
                            Title = "Junior ML Engineer (Contract)",
                            WorkArrangementId = 3
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePosted = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Support product planning, write user stories, coordinate with dev/design, and track feature delivery.",
                            EmployerId = 1,
                            JobCategoryId = 1,
                            JobTypeId = 1,
                            Location = "Singapore (CBD)",
                            Salary = 3600m,
                            Title = "Product Associate (Tech)",
                            WorkArrangementId = 2
                        });
                });

            modelBuilder.Entity("SmoothCareers.Domain.JobSeeker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobSeeker");
                });

            modelBuilder.Entity("SmoothCareers.Domain.JobType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(9051),
                            DateUpdated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(9052),
                            Name = "Full-Time",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(9053),
                            DateUpdated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(9054),
                            Name = "Part-Time",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(9055),
                            DateUpdated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(9055),
                            Name = "Internship",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(9057),
                            DateUpdated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(9057),
                            Name = "Contract",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(9058),
                            DateUpdated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(9059),
                            Name = "Temporary",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("SmoothCareers.Domain.SavedJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateSaved")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobPostId")
                        .HasColumnType("int");

                    b.Property<string>("SavedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId");

                    b.ToTable("SavedJob");
                });

            modelBuilder.Entity("SmoothCareers.Domain.WorkArrangement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkArrangement");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(9467),
                            DateUpdated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(9467),
                            Name = "Onsite",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(9469),
                            DateUpdated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(9469),
                            Name = "Hybrid",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(9470),
                            DateUpdated = new DateTime(2026, 1, 11, 12, 56, 0, 591, DateTimeKind.Local).AddTicks(9471),
                            Name = "Remote",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SmoothCareers.Data.SmoothCareersUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SmoothCareers.Data.SmoothCareersUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmoothCareers.Data.SmoothCareersUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SmoothCareers.Data.SmoothCareersUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmoothCareers.Domain.Application", b =>
                {
                    b.HasOne("SmoothCareers.Domain.JobPost", "JobPost")
                        .WithMany("Applications")
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmoothCareers.Domain.JobSeeker", "JobSeeker")
                        .WithMany("Applications")
                        .HasForeignKey("JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPost");

                    b.Navigation("JobSeeker");
                });

            modelBuilder.Entity("SmoothCareers.Domain.JobPost", b =>
                {
                    b.HasOne("SmoothCareers.Domain.Employer", "Employer")
                        .WithMany("JobPosts")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmoothCareers.Domain.JobCategory", "JobCategory")
                        .WithMany("JobPosts")
                        .HasForeignKey("JobCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmoothCareers.Domain.JobType", "JobType")
                        .WithMany("JobPosts")
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmoothCareers.Domain.WorkArrangement", "WorkArrangement")
                        .WithMany("JobPosts")
                        .HasForeignKey("WorkArrangementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("JobCategory");

                    b.Navigation("JobType");

                    b.Navigation("WorkArrangement");
                });

            modelBuilder.Entity("SmoothCareers.Domain.SavedJob", b =>
                {
                    b.HasOne("SmoothCareers.Domain.JobPost", "JobPost")
                        .WithMany()
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPost");
                });

            modelBuilder.Entity("SmoothCareers.Domain.Employer", b =>
                {
                    b.Navigation("JobPosts");
                });

            modelBuilder.Entity("SmoothCareers.Domain.JobCategory", b =>
                {
                    b.Navigation("JobPosts");
                });

            modelBuilder.Entity("SmoothCareers.Domain.JobPost", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("SmoothCareers.Domain.JobSeeker", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("SmoothCareers.Domain.JobType", b =>
                {
                    b.Navigation("JobPosts");
                });

            modelBuilder.Entity("SmoothCareers.Domain.WorkArrangement", b =>
                {
                    b.Navigation("JobPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
